#include "VOLTAGE_SENSOR.h"

u16 VOLTAGE_SAMPLE_VALUE[10] =
{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };

u16 VOLTAGE_SAMPLE1_VALUE[10] =
{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };

void VOLTAGE_SAMPLE(u8 index)
{
	VOLTAGE_SAMPLE1_VALUE[index] = Get_Adc(ADC_Channel_1);
	VOLTAGE_SAMPLE_VALUE[index] = Get_Adc(ADC_Channel_0);
}

void Get_VOLTAGE_VALUE(ADC_Data *VOLTAGE_SENSOR_ADC,ADC_Data *VOLTAGE_SENSOR_ADC1)
{
	VOLTAGE_SENSOR_ADC->adc_digital = 1*(VOLTAGE_SAMPLE_VALUE[0]
	+ VOLTAGE_SAMPLE_VALUE[1] + VOLTAGE_SAMPLE_VALUE[2]
			+ VOLTAGE_SAMPLE_VALUE[3] + VOLTAGE_SAMPLE_VALUE[4]
			+ VOLTAGE_SAMPLE_VALUE[5] + VOLTAGE_SAMPLE_VALUE[6]
			+ VOLTAGE_SAMPLE_VALUE[7] + VOLTAGE_SAMPLE_VALUE[8]
			+ VOLTAGE_SAMPLE_VALUE[9]) / 10;
	
	VOLTAGE_SENSOR_ADC1->adc_digital =( VOLTAGE_SAMPLE1_VALUE[0]
			+ VOLTAGE_SAMPLE1_VALUE[1] + VOLTAGE_SAMPLE1_VALUE[2]
			+ VOLTAGE_SAMPLE1_VALUE[3] + VOLTAGE_SAMPLE1_VALUE[4]
			+ VOLTAGE_SAMPLE1_VALUE[5] + VOLTAGE_SAMPLE1_VALUE[6]
			+ VOLTAGE_SAMPLE1_VALUE[7] + VOLTAGE_SAMPLE1_VALUE[8]
			+ VOLTAGE_SAMPLE1_VALUE[9]) / 10;

	VOLTAGE_SENSOR_ADC->voltage = (float) VOLTAGE_SENSOR_ADC->adc_digital;
			//* (3.3 / 4096);
	
	VOLTAGE_SENSOR_ADC1->voltage = (float) VOLTAGE_SENSOR_ADC1->adc_digital;
			//* (3.3 / 4096);

	VOLTAGE_SENSOR_ADC->data_value = 510000 * VOLTAGE_SENSOR_ADC->voltage/(VOLTAGE_SENSOR_ADC1->voltage-VOLTAGE_SENSOR_ADC->voltage);
}
